### ISSUE TITLE
kong 2.1.4不兼容

### ISSUE THREAD

**Issue by foolenough** [anjia0532/kong-plugin-sync-eureka#2]
插件执行命令的时候调用的sync_eureka_plugin = plugins:select_by_cache_key("plugins:sync-eureka::::")
kong 2.1.4版本里, plugin, route等表结构增加了ws_id字段， cache_key也由原本的"plugins:sync-eureka::::"变成了"plugins:sync-eureka::::::${ws_id}", 导致无法执行响应的操作。
kong 2.0.4上该插件是可以用的。
kong 2.1.3，2.1.4都不行，中间其它版本未确认。

**Comment by anjia0532** [comment]
我们一直用的是1.x的，2.x的换用了外部同步（基于python），主要原因是用了各种姿势（除非用redis），否则都会存在重复执行问题（有几个实例执行几次），业务高峰期时，存在同步程序异常挂起的问题

**Comment by wehxr** [comment]
可以开源下python的同步脚本吗？

**Comment by anjia0532** [comment]
@huangguang93 跟业务逻辑耦合较大，不太好分拆。其实很简单，自己研究一下api就能写出来。
